Transform: AWS::Serverless-2016-10-31
Description: |
  hagah-backend
  Sample SAM Template for hagah-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  hagahJwt:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./layer/jwt
      CompatibleArchitectures:
        - arm64
      CompatibleRuntimes:
        - nodejs22.x
    Metadata:
      BuildMethod: nodejs22.x
      BuildArchitecture: arm64
  hagahMysql:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./layer/mysql2
      CompatibleArchitectures:
        - arm64
      CompatibleRuntimes:
        - nodejs22.x
    Metadata:
      BuildMethod: nodejs22.x
      BuildArchitecture: arm64
  
  AuthSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./function/auth-signup
      Handler: index.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Layers:
        - !Ref hagahJwt
        - !Ref hagahMysql
      Events:
        AuthSignup:
          Type: Api
          Properties:
            Path: /auth/signup
            Method: post
      Environment:
        Variables:
          NODE_ENV: production

  AuthLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./function/auth-login
      Handler: index.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - arm64
      Layers:
        - !Ref hagahJwt
        - !Ref hagahMysql
      Events:
        AuthLogin:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
      Environment:
        Variables:
          NODE_ENV: production
Metadata:
  AWS::Composer::Groups:
    Group:
      Label: layer
      Members:
        - hagahJwt
        - hagahMysql
    FunctionGroup:
      Label: functions
      Members:
        - AuthSignupFunction
        - AuthLoginFunction